# This is workflow name
name: Hello

# runs on a trigger
on: 
  workflow_dispatch: #push:
                        #branches: [main]
# These are jobs inside the workflow
jobs:

# This is the name of the job
greet:
  

  # This is github runner, each job runs on a runner
  runs-on: ubuntu-latest
  steps:
    - name: say hello to users
      run: echo "Hello Dosto"
    - name: say hello to username
      run: echo "hello $USER"

show-version:
  runs-on: ubuntu-latest
  steps:
    - name: show what is the version of python, docker, etc..
      run: docker --version && python --version
